"""Agent entity: state, weight, solution, and LLM interaction methods."""

from dataclasses import dataclass, field

from .providers.base import BaseLLMProvider


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Solution:
    """A code solution generated by an agent."""
    code: str
    generation_round: int = 0  # 0 = initial, 1+ = refinement round


@dataclass
class Agent:
    """A single debating agent with its own LLM provider.

    Attributes:
        id: Stable identifier (0-indexed).
        provider: The LLM backend this agent uses.
        weight: Current normalized weight (initially 1/N).
        cumulative_gamma: Historical cumulative consistency score Γ_i.
        current_solution: The agent's latest code solution.
        alive: Whether this agent is still in the debate.
    """
    id: int
    provider: BaseLLMProvider
    weight: float = 0.2
    cumulative_gamma: float = 0.0
    current_solution: Solution | None = None
    alive: bool = True


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

INITIAL_SOLUTION_SYSTEM = """\
You are an expert Python programmer competing in a LeetCode challenge.
Generate a correct, efficient solution for the given problem.
Output ONLY the Python code in the following format — no explanations, no markdown fences:

class Solution:
    def {method_signature}(self, ...):
        # your implementation
"""

INITIAL_SOLUTION_USER = """\
Problem: {title}
Difficulty: {difficulty}

Description:
{description}

Constraints:
{constraints}

Write the solution. Output ONLY the code."""


REFINE_SYSTEM = """\
You are an expert code reviewer. Analyze the strengths of other solutions 
and refine your own solution to be the best possible answer.

Rules:
1. Study other solutions for algorithmic insights and edge-case handling.
2. Incorporate the best ideas into your solution.
3. Fix any issues you find in your current solution.
4. Output ONLY the refined Python code — no explanations."""


REFINE_USER = """\
Problem: {title}
Description:
{description}

--- YOUR CURRENT SOLUTION ---
{my_solution}

--- OTHER SOLUTIONS IN THE POOL ---
{other_solutions}

Refine your solution and output ONLY the code."""


VOTE_SYSTEM = """\
You are a code quality judge. Rank solutions by correctness, efficiency, 
and code clarity. Be objective and critical.

Output format: a Python list of solution indices, from best to worst.
Example: [3, 1, 5] means Solution 3 is best, then 1, then 5.
Do NOT include your own solution index.
Output ONLY the list — no other text."""


VOTE_USER_TOP_K = """\
Problem: {title}
Description:
{description}

Solutions:
{solutions_list}

Rank the TOP {K} solutions (excluding your own, index {my_index}).
Output ONLY a list like: [i, j, ...]"""


VOTE_USER_BEST_1 = """\
Problem: {title}
Description:
{description}

Solutions:
{solutions_list}

Pick the SINGLE BEST solution (excluding your own, index {my_index}).
Output ONLY the index as a single integer, e.g.: 2"""


# ---------------------------------------------------------------------------
# Agent methods
# ---------------------------------------------------------------------------

def generate_initial_solution(
    agent: Agent,
    problem: dict,
) -> tuple[Solution, dict[str, str], str]:
    """Generate the initial solution for a problem.

    Args:
        agent: The agent generating the solution.
        problem: Dict with 'title', 'difficulty', 'description', 'constraints',
                 'function_signature'.

    Returns:
        (Solution, prompt_dict, response_text)
        prompt_dict = {"system": ..., "user": ...}
        response_text = raw LLM output
    """
    sig = problem.get("function_signature", "solution(self, ...)")
    system = INITIAL_SOLUTION_SYSTEM.format(method_signature=sig)
    user = INITIAL_SOLUTION_USER.format(
        title=problem.get("title", ""),
        difficulty=problem.get("difficulty", "unknown"),
        description=problem.get("description", ""),
        constraints=problem.get("constraints", ""),
    )
    response_raw = agent.provider.generate(system, user)
    code = _strip_code_fences(response_raw)
    solution = Solution(code=code, generation_round=0)
    agent.current_solution = solution
    prompt = {"system": system, "user": user}
    return solution, prompt, response_raw


def refine_solution(
    agent: Agent,
    problem: dict,
    all_solutions: dict[int, Solution],
) -> tuple[Solution, dict[str, str], str]:
    """Refine the agent's solution by studying others.

    Args:
        agent: The agent refining.
        problem: Problem dict.
        all_solutions: Map of agent_id → Solution for all alive agents.

    Returns:
        (Solution, prompt_dict, response_text)
    """
    my_code = (agent.current_solution.code if agent.current_solution
               else "No solution yet.")
    other_codes = []
    for aid, sol in all_solutions.items():
        if aid != agent.id:
            other_codes.append(f"[Agent {aid}]:\n{sol.code}\n")

    other_text = "\n".join(other_codes) if other_codes else "(no other solutions)"

    user = REFINE_USER.format(
        title=problem.get("title", ""),
        description=problem.get("description", ""),
        my_solution=my_code,
        other_solutions=other_text,
    )
    response_raw = agent.provider.generate(REFINE_SYSTEM, user)
    code = _strip_code_fences(response_raw)
    prev_round = agent.current_solution.generation_round if agent.current_solution else 0
    solution = Solution(code=code, generation_round=prev_round + 1)
    agent.current_solution = solution
    prompt = {"system": REFINE_SYSTEM, "user": user}
    return solution, prompt, response_raw


def vote(
    agent: Agent,
    problem: dict,
    solution_map: dict[int, Solution],
    K: int,
    my_index: int,
) -> tuple[list[int], dict[str, str], str]:
    """Vote for the best solutions.

    Args:
        agent: The voting agent.
        problem: Problem dict.
        solution_map: Map of agent_id → Solution for all alive agents.
        K: Number of solutions to vote for (1 = Best-1, >1 = Top-K).
        my_index: Agent's index in the solution listing (to exclude self).

    Returns:
        (voted_agent_ids, prompt_dict, response_text)
    """
    # Build solutions list for the prompt, excluding self
    solutions_parts = []
    agent_ids = []
    for aid, sol in solution_map.items():
        if aid == agent.id:
            continue
        idx = len(agent_ids) + 1  # 1-indexed display
        solutions_parts.append(f"[Solution {idx}]:\n{sol.code}\n")
        agent_ids.append(aid)

    solutions_text = "\n".join(solutions_parts)

    if K == 1:
        system = VOTE_SYSTEM
        user = VOTE_USER_BEST_1.format(
            title=problem.get("title", ""),
            description=problem.get("description", ""),
            solutions_list=solutions_text,
            my_index=my_index,
        )
    else:
        system = VOTE_SYSTEM
        user = VOTE_USER_TOP_K.format(
            title=problem.get("title", ""),
            description=problem.get("description", ""),
            solutions_list=solutions_text,
            K=K,
            my_index=my_index,
        )

    response_raw = agent.provider.generate(system, user)
    voted = _parse_vote_response(response_raw, agent_ids, K)
    prompt = {"system": system, "user": user}
    return voted, prompt, response_raw


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _strip_code_fences(code: str) -> str:
    """Remove markdown ```python ... ``` fences from generated code."""
    code = code.strip()
    if code.startswith("```"):
        # Remove opening fence line
        lines = code.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        # Remove closing fence line
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        code = "\n".join(lines)
    return code.strip()


def _parse_vote_response(response: str, agent_ids: list[int], K: int) -> list[int]:
    """Parse LLM vote response into agent_id list.

    Handles formats: [3, 1, 5], [3,1,5], "3", 3.
    """
    import ast
    response = response.strip()

    # Try parsing as Python literal
    try:
        result = ast.literal_eval(response)
        if isinstance(result, int):
            result = [result]
        if isinstance(result, list):
            # Convert display indices (1-based) to agent_ids
            out = []
            for item in result:
                if isinstance(item, int) and 1 <= item <= len(agent_ids):
                    out.append(agent_ids[item - 1])
            return out[:K]
    except (ValueError, SyntaxError):
        pass

    # Fallback: extract integers with regex
    import re
    nums = re.findall(r'\d+', response)
    out = []
    seen = set()
    for n_str in nums:
        n = int(n_str)
        if 1 <= n <= len(agent_ids):
            aid = agent_ids[n - 1]
            if aid not in seen:
                out.append(aid)
                seen.add(aid)
    return out[:K]
